language: node_js

node_js:
  - 13.7.0

cache:
  directories:
  - "node_modules"

notifications:
  email:
    on_success: never

branches:
  only:
    - site

install:
  - yarn

script:
  - yarn run build
